### ISSUE TITLE
USB port 2.0 is not available

### ISSUE THREAD

**Issue by lengwangye** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#3]
USB port 2.0 is not available

**Comment by extric99** [comment]
Can you please explain the issue in more detail because I don’t understand what you mean. Not all USB ports are mapped to USB 2 or 3 to stay under the 15 port limit. If you want a different mapping you can change the SDDT yourself.

**Comment by lengwangye** [comment]
Enable USBInjectAll.kext This file USB2.0 port is invalid, cancel this file USB3.0 invalid

**Comment by lengwangye** [comment]
Can I leave a contact information

**Comment by lengwangye** [comment]
Can you leave a contact information?

**Comment by extric99** [comment]
The USB ports can be configured in multiple ways on a Hackintosh and I used the USBInjectAll.kext + SSDT-UIAC.aml approach. They work together where the kext enables all the USB ports and the SSDT limits the ports to stay under the 15 port limit and specifies which one is USB2, USB3 or internal. My layout is detailed on the main page:

USB3 is SS
USB2 is HS

It is normal that some USB ports will be disabled (see motherboard layout) or not work at USB3 speeds.  
If you want a different layout you will need to modify the SSDT yourself.
In case this does not answer the question because I am not sure about the issue, please post a comprehensive description in your native language for me to try to google translate.

https://github.com/extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i7-9900k-5700XT/blob/master/screenshot/Screenshot_USB_Layout.png


https://github.com/extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i7-9900k-5700XT/blob/master/screenshot/Screenshot_USB.png

**Comment by lengwangye** [comment]
Do you have a WeChat account?

**Comment by extric99** [comment]
Please describe the issue here and i will try to help. 
If you want other USB2 ports mapped you will need to change the configuration  yourself which can be done quickly using hackintool. You can then replace the files in the EFi.

**Comment by user1121114685** [comment]
mark,The same problem appeared to me. Now Gigabyte official website has updated the bios of f10h, and now it supports cfg lock setting

**Comment by lengwangye** [comment]
> 马克，我也遇到了同样的问题。现在技嘉官方网站已经更新了f10h的BIOS，现在支持cfg锁设置
Have you solved it?
